import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'firebase_options.dart'; // Generated by flutterfire configure

// Auth and onboarding screens
import 'package:smart_solar/login_screen.dart';
import 'package:smart_solar/signup_screen.dart';
import 'package:smart_solar/verify_email.dart';
import 'package:smart_solar/verified_email.dart';
import 'package:smart_solar/phone_verify.dart';
import 'package:smart_solar/verify_phone.dart';
import 'package:smart_solar/verified_phone.dart';
import 'package:smart_solar/password.dart';
import 'package:smart_solar/profile_screen.dart';
import 'package:smart_solar/welcome_screen.dart';

// Main app screens
import 'package:smart_solar/home_screen.dart';
import 'package:smart_solar/booking_screen.dart';
import 'package:smart_solar/booking_history.dart';
import 'package:smart_solar/profile.dart';

// New cart and checkout screens
import 'package:smart_solar/cart_screen.dart';
import 'package:smart_solar/checkout_screen.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  // Get login state from SharedPreferences to determine initial route
  final prefs = await SharedPreferences.getInstance();
  final isLoggedIn = prefs.getBool('isLoggedIn') ?? false;

  runApp(MyApp(isLoggedIn: isLoggedIn));
}

class MyApp extends StatelessWidget {
  final bool isLoggedIn;

  const MyApp({super.key, required this.isLoggedIn});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Smart Solar',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        primaryColor: const Color(0xFF00A99D),
        colorScheme: ColorScheme.fromSeed(
          seedColor: const Color(0xFF00A99D),
          primary: const Color(0xFF00A99D),
        ),
      ),
      initialRoute: isLoggedIn ? '/home' : '/welcome',
      routes: {
        // Auth and onboarding routes
        '/welcome': (context) => WelcomeScreen(),
        '/login': (context) => LoginScreen(),
        '/signup': (context) => SignUpScreen(),
        '/verify-email': (context) => VerifyEmailScreen(email: ''),
        '/email-verified': (context) => EmailVerifiedScreen(
          onNext: () => Navigator.pushNamed(context, '/phone-number'),
        ),
        '/phone-number': (context) => PhoneNumberScreen(),
        '/verify-phone': (context) => VerifyPhoneScreen(
          phoneNumber: '',
          verificationId: '',
        ),
        '/phone-verified': (context) => PhoneVerifiedScreen(
          onNext: () => Navigator.pushNamed(context, '/password'),
        ),
        '/password': (context) => CreatePasswordScreen(),
        '/name-screen': (context) => ProfileNameScreen(),

        // Main app routes
        '/home': (context) => HomeScreen(),
        '/booking': (context) => BookingScreen(serviceType: 'Solar System'),
        '/booking-history': (context) => BookingHistoryScreen(),
        '/profile': (context) => ProfileScreen(),

        // New cart and checkout routes
        '/cart': (context) => CartScreen(),
      },
    );
  }
}